# Generated by Django 5.2.12 on 2026-03-20 12:17

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=api.models.upload_to,
                        validators=[api.models.validate_image],
                    ),
                ),
                (
                    "friends",
                    models.ManyToManyField(
                        blank=True, related_name="friends", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(blank=True, default="", max_length=40)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Other", "Other"),
                            ("Restaurant", "Restaurant"),
                            ("Transport", "Transport"),
                            ("Rent", "Rent"),
                            ("Alcohol", "Alcohol"),
                            ("Groceries", "Groceries"),
                            ("Tickets", "Tickets"),
                        ],
                        default=("Other", "Other"),
                        max_length=15,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=8
                    ),
                ),
                (
                    "splitted",
                    models.BooleanField(
                        choices=[(True, "Total"), (False, "Each")], default=True
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("is_paid", models.BooleanField(default=False)),
                ("settled", models.BooleanField(default=False)),
                ("hash", models.TextField(blank=True, default="")),
                (
                    "ower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ower",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FriendsInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invited",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invited",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sender",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GroupExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=8
                    ),
                ),
                ("expenses", models.ManyToManyField(blank=True, to="api.expense")),
            ],
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group_name",
                    models.TextField(blank=True, default="New group", max_length=40),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=api.models.upload_to,
                        validators=[api.models.validate_image],
                    ),
                ),
                (
                    "admins",
                    models.ManyToManyField(
                        blank=True, related_name="admins", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        related_name="members", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "group_expenses",
                    models.ManyToManyField(blank=True, to="api.groupexpense"),
                ),
            ],
        ),
    ]
