from django.urls import path
from .views import (
    GetUserByID,
    GetGroupExpenses,
    GetUsersGroups,
    GetChartValues,
    GetUsersExpenses,
    AddExpense,
    InviteFriend,
    AcceptInvitation,
    DeclineInvitation,
    AddToGroup,
    LeaveGroup,
    SeeFriends,
    SetAsPaid,
    Settle,
    GetUsersSummarize,
    FindFriends,
    RemoveFriend,
    AcceptInvitationByUser,
    DeclineInvitationByUser,
    CancelInvitationByUser,
    GetInvitations,
    GetNotifications,
    SetAvatar,
    GetAvatar,
    GetGroupAvatar
)

urlpatterns = [
    path("username", GetUserByID.as_view()),
    path("group", GetUsersGroups.as_view()),
    path("groupExpenses", GetGroupExpenses.as_view()),
    path("chartData", GetChartValues.as_view()),
    path("userExpenses", GetUsersExpenses.as_view()),
    path("addExpense", AddExpense.as_view()),
    path("seeFriends", SeeFriends.as_view()),
    path("inviteFriend", InviteFriend.as_view()),
    path("removeFriend", RemoveFriend.as_view()),
    path("declineInvitation", DeclineInvitation.as_view()),
    path("declineInvitation/byUser", DeclineInvitationByUser.as_view()),
    path("cancelInvitation/byUser", CancelInvitationByUser.as_view()),
    path("acceptInvitation", AcceptInvitation.as_view()),
    path("acceptInvitation/byUser", AcceptInvitationByUser.as_view()),
    path("addToGroup", AddToGroup.as_view()),
    path("leaveGroup", LeaveGroup.as_view()),
    path("setAsPaid", SetAsPaid.as_view()),
    path("settle", Settle.as_view()),
    path("summarize", GetUsersSummarize.as_view()),
    path('findFriends/<str:username>', FindFriends.as_view(), name="find_friends"),
    path("getInvitations", GetInvitations.as_view()),
    path("getNotifications", GetNotifications.as_view()),
    path("setAvatar", SetAvatar.as_view()),
    path("getAvatar/<int:id>", GetAvatar.as_view()),
    path("getGroupAvatar/<int:id>", GetGroupAvatar.as_view()),
]
