from django.urls import path
from .views import (
    GetUserByID,
    GetUsersGroups,
    GetUsersExpenses,
    AddExpense,
    SetAsPaid,
    Settle,
    GetUsersSummarize,
    SetAvatar,
    GetAvatar,
    CreateNewUser,
    SearchUsersToAdd
)
from .groups.views import (
    GetGroupExpenses,
    GetChartValues,
    AddToGroup,
    LeaveGroup,
    GetGroupAvatar,
    SetGroupName,
    CreateNewGroup,
    AddUsertoGroup,
    DeleteGroup,
)

from .friends.views import (
    InviteFriend,
    AcceptInvitation,
    DeclineInvitation,
    SeeFriends,
    FindFriends,
    RemoveFriend,
    AcceptInvitationByUser,
    DeclineInvitationByUser,
    CancelInvitationByUser,
    GetInvitations,
    GetNotifications,
)

urlpatterns = [
    path("sign-up", CreateNewUser.as_view()),
    path("username", GetUserByID.as_view()),
    path("group", GetUsersGroups.as_view()),
    path("groupExpenses/<int:id>", GetGroupExpenses.as_view()),
    path("chartData/<int:id>", GetChartValues.as_view()),
    path("userExpenses", GetUsersExpenses.as_view()),
    path("addExpense", AddExpense.as_view()),
    path("seeFriends", SeeFriends.as_view()),
    path("inviteFriend", InviteFriend.as_view()),
    path("removeFriend", RemoveFriend.as_view()),
    path("declineInvitation", DeclineInvitation.as_view()),
    path("declineInvitation/byUser", DeclineInvitationByUser.as_view()),
    path("cancelInvitation/byUser", CancelInvitationByUser.as_view()),
    path("acceptInvitation", AcceptInvitation.as_view()),
    path("acceptInvitation/byUser", AcceptInvitationByUser.as_view()),
    path("addToGroup", AddToGroup.as_view()),
    path("leaveGroup", LeaveGroup.as_view()),
    path("deleteGroup", DeleteGroup.as_view()),
    path("setAsPaid", SetAsPaid.as_view()),
    path("settle", Settle.as_view()),
    path("summarize", GetUsersSummarize.as_view()),
    path('findFriends/<str:username>', FindFriends.as_view(), name="find_friends"),
    path('searchUsersToAdd/<str:username>/<int:id>', SearchUsersToAdd.as_view(), name="search_users"),
    path("getInvitations", GetInvitations.as_view()),
    path("getNotifications", GetNotifications.as_view()),
    path("setAvatar", SetAvatar.as_view()),
    path("setGroupName", SetGroupName.as_view()),
    path("getAvatar/<int:id>", GetAvatar.as_view()),
    path("getGroupAvatar/<int:id>", GetGroupAvatar.as_view()),
    path("createGroup", CreateNewGroup.as_view()),
    path("addUserToGroup", AddUsertoGroup.as_view()),
]
